openapi: 3.0.0
info:
  title: demo
  version: '1.0'
  description: First experiment with Stoplight and the workflow for creating a spring-boot project from this spec
  contact:
    name: Paolo
    email: paolo.contessi@gmail.com
servers:
  - url: 'http://localhost:8080'
paths:
  '/people/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: getById
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
      operationId: get-people-id
    post:
      summary: createNew
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
      operationId: post-people-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
    put:
      summary: replace
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
      operationId: put-people-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
    patch:
      summary: edit
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
      operationId: patch-people-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
    delete:
      summary: deleteById
      tags: []
      responses:
        '204':
          description: No Content
      operationId: delete-people-id
components:
  schemas:
    Person:
      title: Person
      type: object
      description: ''
      properties:
        id:
          type: string
        name:
          type: string
        surname:
          type: string
        age:
          type: integer
  securitySchemes: {}
security: []
