openapi: 3.0.0
info:
  title: demo
  version: '1.0'
  description: First experiment with Stoplight and the workflow for creating a spring-boot project from this spec
  contact:
    name: Paolo
    email: paolo.contessi@gmail.com
servers:
  - url: 'http://localhost:8080'
paths:
  '/people/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: getById
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples: {}
      operationId: get-people-id
    post:
      summary: createNew
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-people-id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
    put:
      summary: replace
      tags: []
      responses: {}
      operationId: put-people-id
    patch:
      summary: edit
      tags: []
      responses: {}
      operationId: patch-people-id
    delete:
      summary: deleteById
      tags: []
      responses: {}
      operationId: delete-people-id
components:
  schemas:
    Person:
      title: Person
      type: object
      properties:
        id:
          type: string
  securitySchemes: {}
security: []
